// Speaker script for the talk "Sell the Styles, Ship the Space": one entry per slide, shared by the deck (presenter notes) and the transcript page.

/** One slide's script: its deck id, a human label, and the spoken text with [bracketed] cues for builds and cuts. */
export interface ScriptEntry {
	id: string
	label: string
	text: string
}

/** The script in slide order. Use typographic apostrophes (’) only: a straight one breaks this file. */
export const SCRIPT: ScriptEntry[] = [
	{ id: 'cover', label: 'Sell the Styles, Ship the Space', text: 'You buy four weights of a typeface, Regular to Bold. You get four files. You could have had one variable font covering exactly those weights, and nobody will sell it to you. That’s what this talk is about.' },
	{ id: 'hook', label: 'The problem', text: 'Here’s the usual order. Regular, Medium, SemiBold and Bold. [Next] Four static files. [Next] What you could get instead is one file that does everything in between: any weight from Regular to Bold, and nothing past it.' },
	{ id: 'unused', label: 'Made, rarely sold', text: 'Foundries make variable fonts. They just don’t sell many. [Next] Kris Sowersby at Klim said they’d had maybe four requests since launch. [Next] Christopher Slye at Type Network said they weren’t exactly burning up the charts. [Next] And Sowersby said why: they have to be priced as the full family, because that’s what they are.' },
	{ id: 'price', label: 'A bundle', text: 'That’s the catch. [Next] Mark Simonson says most of his customers buy one to six styles out of forty-eight. [Next] But a variable font comes as a bundle. At Dalton Maag, two single styles cost sixty-four pounds. The cheapest variable font is ninety-five, and it includes every weight. If you only wanted two, you pay half again.' },
	{ id: 'styles', label: 'Styles and spaces', text: 'Underneath that is a mismatch. Designers think in named styles. Foundries build design spaces. [Next] Nick Shinn says dropping the names Regular and Bold seems impossible. [Next] And John Hudson calls named instances signposts, pins on a map.' },
	{ id: 'mm', label: 'Multiple Masters', text: 'We’ve tried selling the space before. Adobe’s Multiple Master fonts, in the nineties, shipped a whole design space. [Next] Thomas Phinney, who was at Adobe, said they sold well, but most people only used the instances that came with them. Adobe would have made their lives easier selling separate fonts with clear names. So don’t sell sliders. Sell the styles, and put the space between them in the box.' },
	{ id: 'adoption', label: 'The web went variable', text: 'Meanwhile the web went variable anyway: eleven percent of mobile pages in 2020, forty-one percent in 2025. Most of that is free fonts, though. People use variable fonts when they cost nothing. Whether they’ll pay for them is still an open question.' },
	{ id: 'suite', label: 'What static buyers lose', text: 'People who buy statics lose more than file size. Three of our own type tools don’t work without a variable font. [Next] axisRhythm, [Next] hoverBoldly, [Next] and magnetType. Five more lose their main effect. [Next] Bolding a menu item on hover shifts the line about three and a half pixels. hoverBoldly removes that shift, but only with a variable font.' },
	{ id: 'crossover', label: 'File size', text: 'Then there’s the file-size objection. Each static weight of Inter adds about a hundred and ten kilobytes. [Next] Clamp the variable font to the weights you bought, and it’s already smaller at two neighbouring weights: a hundred and sixty-two kilobytes against two hundred and twenty-six. By seven weights it’s seventy-two percent smaller. [Next] Keeping optical size costs more, so pin the axes the customer didn’t buy.' },
	{ id: 'survey', label: 'The survey', text: 'How are variable fonts actually sold? We checked every foundry in the Type Foundry Directory. [Next] Three hundred and ninety-four of them: buy pages, licences, store data. [Next] Then a second pass tried to overturn every call we’d made, and changed twenty-seven.' },
	{ id: 'funnel', label: 'The funnel', text: 'Here’s how it falls out. [Next] Two hundred and thirteen sell variable fonts. [Next] A hundred and nineteen sell one without the family, usually the whole design space at close to the family price. [Next] Twenty-two sell a smaller variable font, cut from the family. [Next] And none sell one cut to the styles you bought.' },
	{ id: 'precedent', label: 'Precedent', text: 'Those twenty-two matter. Each one sells a whole width, or a whole optical size, as its own variable font, usually for about a third of the family price. And they still sell families.' },
	{ id: 'gap', label: 'The gap', text: 'What nobody sells is the range you bought. Buy Regular to Bold, ask for one file, and none of the stores we checked will give it to you.' },
	{ id: 'asked', label: 'Asked for since 2015', text: 'People have asked for this for years. [Next] In 2015 Nick Sherman suggested a Light to Medium range should cost less than Thin to Black. [Next] In 2018 John Hudson asked for a tool that cuts a design space down. [Next] In 2022 Nick Shinn asked for a distributor app that does exactly that. The pricing idea is eleven years old. Nobody’s built the shop that sends the matching file.' },
	{ id: 'opportunity', label: 'The pieces', text: 'And the pieces exist. [Next] Twenty-two foundries already license part of a design space. [Next] Fontdue already builds a file for every order. [Next] And Google Fonts already cuts fonts at delivery, but only whole axes. Ask for weights four hundred to seven hundred and you still get one hundred to nine hundred.' },
	{ id: 'how', label: 'How it works', text: 'It works like this. [Next] The customer picks styles, like always. [Next] At checkout, the weight axis is clamped to what they bought, and axes they didn’t license are pinned. [Next] The file is renamed for the range, and the font menu lists Regular, Medium, SemiBold and Bold. [Next] It’s delivered with the statics. [Next] If someone buys Regular and Bold but nothing between, you either send two files, or decide what the weights in between cost.' },
	{ id: 'demo', label: 'Is it practical?', text: 'Is it practical? I should say vf-clamp is our tool; underneath, it’s fontTools. [Cut to demo: load Encode Sans, pick Regular, Medium, SemiBold and Bold, download, end on the Regular to Bold result.] Four weights in, one file out, a third smaller than the full font. And a font engineer who reviewed this talk found bugs in it, which we’ve fixed.' },
	{ id: 'objections', label: 'Objections', text: 'There are good objections. Thomas Phinney warned that slicing as a regular part of business makes retail complicated. The clamp takes a few seconds and can be cached; pricing the weights in between is the harder part. Nick Shinn worried cheap variable fonts would erode family prices. Twenty-two foundries sell slices and still sell families, though nobody publishes the numbers. Scott-Martin Kosofsky warned that slices get undercut by the whole thing. Sell both: the range now, the full space as an upgrade. Alex Visi said file-size savings only hold sometimes. That’s true for a full variable font, not a clamped one. And desktop apps still handle variable fonts badly, which is why you ship the statics too.' },
	{ id: 'ask', label: 'Three asks', text: 'Three asks. [Next] Foundries: keep selling styles, and put a variable font for the range in the box. [Next] Storefronts: add a clamp step at checkout, and run one pilot to see if anyone pays for it. [Next] Licence authors: twenty-seven of the thirty-five licences we read never mention variable fonts. Write down the range, allow any weight inside it, and fence off the rest.' },
	{ id: 'close', label: 'Close', text: 'Designers are going to keep thinking in styles. That’s fine. Keep selling them styles, and ship the space between them with the order.' },
	{ id: 'about', label: 'Who we are', text: 'We’re Overpunch. We’ve built websites for type foundries for fifteen years, we make type tools for the web, and we’re building Typetin, a storefront for independent foundries. Try vf-clamp, and read the paper, at vfclamp.com. Thank you.' },
]

/** Script text keyed by slide id, for the deck's presenter notes. */
export const SCRIPT_NOTES: Record<string, string> = Object.fromEntries(SCRIPT.map(e => [e.id, e.text]))

/** Strips [bracketed] build and cut cues, leaving only the spoken words. */
export function spoken(text: string): string {
	return text.replace(/\s*\[[^\]]*\]\s*/g, ' ').replace(/\s+/g, ' ').trim()
}
