// Talk deck engine — a keyboard-driven 1920×1080 slide stage built from the Type Tools site system: tool palettes, Merriweather display type, staggered entrances, count-ups and presenter notes.
// Synced automatically by type-tools/scripts/sync-sites.mjs to sites that have site/src/content/talkScript.ts.
// DO NOT edit this file inside a submodule — edit type-tools/shared/talk/engine.tsx instead.
'use client'

import { Children, useCallback, useEffect, useLayoutEffect, useState, type CSSProperties, type ReactNode } from 'react'
import { toolBg, toolFg, toolFgMuted, toolFgSubtle, toolFgFaint, toolPanel, type ToolId } from '../../lib/toolColors'

/** External link styled for the deck: inherits colour, hairline underline, opens in a new tab. */
export function A({ href, children }: { href: string; children: ReactNode }) {
	return <a href={href} target="_blank" rel="noopener noreferrer" style={{ color: 'inherit', textDecoration: 'underline', textDecorationThickness: 1, textUnderlineOffset: 4, textDecorationColor: 'color-mix(in oklch, currentColor 35%, transparent)' }}>{children}</a>
}


/** Stage size in CSS px; the stage is scaled to fit the viewport. */
export const STAGE_W = 1920
export const STAGE_H = 1080

/** Monospace stack used by the sites (Tailwind's font-mono). */
export const MONO = 'ui-monospace, SFMono-Regular, Menlo, monospace'

/** One tool's palette tokens, as oklch() strings computed by toolColorsCore. */
export interface Palette {
	bg: string
	fg: string
	muted: string
	subtle: string
	faint: string
	panel: string
}

/** Builds a palette for a tool id from the shared colour system. */
export function palette(id: ToolId): Palette {
	return { bg: toolBg(id), fg: toolFg(id), muted: toolFgMuted(id), subtle: toolFgSubtle(id), faint: toolFgFaint(id), panel: toolPanel(id) }
}


/** A slide: its tool palette, build-step count, presenter notes, optional footer and its content renderer. */
export interface Slide {
	id: string
	tool: ToolId
	/** Number of build steps after the slide appears (0 = everything visible at once). */
	steps: number
	notes: string
	footer?: ReactNode
	render: (step: number) => ReactNode
}

// ── Typographic primitives (scaled from the sites' Hero, labels and OG template) ──────────────

/** Merriweather Light 300; opsz follows the size (7–144 axis), reaching the Hero's 144 at display sizes. */
export function display(size: number, extra?: CSSProperties): CSSProperties {
	const opsz = Math.min(144, Math.max(18, size))
	return { fontFamily: 'var(--font-merriweather), Georgia, serif', fontWeight: 300, fontVariationSettings: `"wght" 300, "opsz" ${opsz}`, fontSize: size, lineHeight: 1.05, ...extra }
}

/** Inline style that sets an entrance delay (ms) for the .vfd-rise keyframe. */
export function rise(ms: number): CSSProperties {
	return { ['--d' as string]: `${ms}ms` } as CSSProperties
}

/** Counts from `from` to `to` (ease-out) once `run` is true; jumps straight to `to` when reduced motion is preferred. */
export function CountUp({ to, from = 0, decimals = 0, run = true, ms = 1100, delay = 250 }: { to: number; from?: number; decimals?: number; run?: boolean; ms?: number; delay?: number }) {
	const [v, setV] = useState(from)
	useEffect(() => {
		let raf = 0
		const still = window.matchMedia('(prefers-reduced-motion: reduce)').matches
		const start = performance.now() + delay
		const tick = (now: number) => {
			if (!run) { setV(from); return }
			if (still) { setV(to); return }
			const t = Math.min(1, Math.max(0, (now - start) / ms))
			setV(from + (to - from) * (1 - Math.pow(1 - t, 3)))
			if (t < 1) raf = requestAnimationFrame(tick)
		}
		raf = requestAnimationFrame(tick)
		return () => cancelAnimationFrame(raf)
	}, [run, to, from, ms, delay])
	return <span style={{ fontVariantNumeric: 'tabular-nums' }}>{v.toFixed(decimals)}</span>
}

/** Uppercase tracked label — the sites' eyebrow / section heading style. */
export function Eyebrow({ children, color }: { children: ReactNode; color?: string }) {
	return <p className="vfd-rise" style={{ fontSize: 22, fontWeight: 500, letterSpacing: '0.18em', textTransform: 'uppercase', color: color ?? 'var(--t-muted)' }}>{children}</p>
}

/** Two-line display title: line 1 in foreground, line 2 italic in the subtle step. */
export function Title({ a, b, size = 104 }: { a: ReactNode; b?: ReactNode; size?: number }) {
	return (
		<h2 style={display(size, { textWrap: 'balance' } as CSSProperties)}>
			<span className="vfd-rise" style={{ display: 'inline-block', ...rise(90) }}>{a}</span>
			{b && <><br /><span className="vfd-rise" style={{ display: 'inline-block', fontStyle: 'italic', color: 'var(--t-subtle)', ...rise(200) }}>{b}</span></>}
		</h2>
	)
}

/** Body copy — Inter Light, muted, relaxed leading. */
export function Body({ children, size = 30, style }: { children: ReactNode; size?: number; style?: CSSProperties }) {
	return <p style={{ fontSize: size, lineHeight: 1.55, color: 'var(--t-muted)', textWrap: 'pretty', ...style } as CSSProperties}>{children}</p>
}

/** Panel card — the sites' card: panel fill, rounded, no border or shadow. */
export function Card({ children, style }: { children: ReactNode; style?: CSSProperties }) {
	return <div style={{ background: 'var(--t-panel)', borderRadius: 20, padding: 40, display: 'flex', flexDirection: 'column', gap: 16, ...style }}>{children}</div>
}

/** Mono step numeral in the faint step ("01"). */
export function Numeral({ children }: { children: ReactNode }) {
	return <p style={{ fontFamily: MONO, fontSize: 22, color: 'var(--t-faint)' }}>{children}</p>
}

/** Quote card: italic Merriweather quote with a tracked attribution label. */
export function Quote({ q, who, size = 44 }: { q: string; who: string; size?: number }) {
	return (
		<Card style={{ padding: 44, gap: 28, height: '100%', justifyContent: 'space-between' }}>
			<p style={display(size, { fontStyle: 'italic', lineHeight: 1.35 })}>{q}</p>
			<Eyebrow>{who}</Eyebrow>
		</Card>
	)
}

/** Fades and lifts its children in once the slide's build step reaches `at`. */
export function Reveal({ at, step, children, style }: { at: number; step: number; children: ReactNode; style?: CSSProperties }) {
	const on = step >= at
	return <div style={{ opacity: on ? 1 : 0, transform: on ? 'none' : 'translateY(16px)', transition: 'opacity 500ms ease, transform 500ms ease', ...style }}>{children}</div>
}

/** OG-template bottom row: source chips left, page number right. */
export function Footer({ left, n, total }: { left: ReactNode; n: number; total: number }) {
	return (
		<div data-slide-footer="" className="vfd-rise" style={{ ...rise(650), position: 'absolute', left: 128, right: 128, bottom: 72, display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 48, fontSize: 22, letterSpacing: '0.04em' }}>
			<p style={{ color: 'var(--t-muted)' }}>{left}</p>
			<p style={{ color: 'var(--t-subtle)', fontVariantNumeric: 'tabular-nums', whiteSpace: 'nowrap' }}>{String(n).padStart(2, '0')} / {total}</p>
		</div>
	)
}

/** One funnel row; the bar grows to its width when revealed. */
export function FunnelRow({ label, count, total, on, strong }: { label: string; count: number; total: number; on: boolean; strong?: boolean }) {
	const w = (count / total) * 720
	return (
		<div style={{ display: 'grid', gridTemplateColumns: '760px 1fr', alignItems: 'center', height: 92, opacity: on ? 1 : 0, transition: 'opacity 500ms ease' }}>
			<p style={{ fontSize: 32, fontWeight: strong ? 500 : 300 }}>{label}</p>
			<div style={{ display: 'flex', alignItems: 'center', gap: 24 }}>
				<div style={{ width: on ? Math.max(w, 4) : 0, height: 52, borderRadius: 4, background: strong ? 'var(--t-fg)' : 'var(--t-panel)', transition: 'width 900ms cubic-bezier(.2,.7,.2,1)' }} />
				<p style={display(52)}><CountUp to={count} run={on} ms={900} delay={150} />{count > 0 && count < total && <span style={{ color: 'var(--t-subtle)' }}> {Math.round((count / total) * 100)}%</span>}</p>
			</div>
		</div>
	)
}

/** Slide frame: eyebrow and title pinned to the top; everything after the title is centred in the space above the footer. */
export function Frame({ eyebrow, children, gap = 40 }: { eyebrow: string; children: ReactNode; gap?: number }) {
	const [head, ...rest] = Children.toArray(children)
	return (
		<div style={{ position: 'absolute', inset: 0, padding: '104px 128px 176px', display: 'flex', flexDirection: 'column', gap }}>
			<Eyebrow>{eyebrow}</Eyebrow>
			{head}
			{rest.length > 0 && <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center', gap }}>{rest.map((c, i) => <div key={i} className="vfd-rise" style={rise(320 + i * 120)}>{c}</div>)}</div>}
		</div>
	)
}

/** Three-up grid of revealed cards. */
export function ThreeUp({ step, children }: { step: number; children: ReactNode[] }) {
	return (
		<div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 32 }}>
			{children.map((c, i) => <Reveal key={i} at={i + 1} step={step} style={{ height: '100%' }}>{c}</Reveal>)}
		</div>
	)
}

/** Base keyframes every talk uses: the slide fade-in and the staggered rise (off under reduced motion). */
const BASE_CSS = `
@keyframes vfd-in { from { opacity: 0; } to { opacity: 1; } }
@keyframes vfd-rise { from { opacity: 0; transform: translateY(18px); } to { opacity: 1; transform: none; } }
.vfd-rise { animation: vfd-rise 700ms cubic-bezier(.2,.7,.2,1) both; animation-delay: var(--d, 0ms); }
@media (prefers-reduced-motion: reduce) { .vfd-rise { animation: none; } }
`

/** Reads the 1-based slide number from the URL hash. */
function slideFromHash(count: number): number {
	if (typeof window === 'undefined') return 0
	const n = parseInt(window.location.hash.replace('#', ''), 10)
	return Number.isFinite(n) ? Math.min(Math.max(n - 1, 0), count - 1) : 0
}

/** The full-viewport deck: scales a 1920×1080 stage, handles keys/clicks/swipes, cross-fades tool palettes. `css` adds the talk's own keyframes. */
export function Deck({ slides, title, css = '' }: { slides: Slide[]; title: string; css?: string }) {
	const [index, setIndex] = useState(0)
	const [step, setStep] = useState(0)
	const [scale, setScale] = useState(1)
	const [showNotes, setShowNotes] = useState(false)

	// Restore position from the hash once mounted (hash is unavailable during SSR).
	useEffect(() => {
		// Read now, before the hash-sync effect below rewrites it; apply on the next frame.
		const fromHash = slideFromHash(slides.length)
		const id = requestAnimationFrame(() => { setIndex(fromHash); setStep(0) })
		return () => cancelAnimationFrame(id)
	}, [slides.length])

	// Fit the stage to the viewport.
	useLayoutEffect(() => {
		const fit = () => setScale(Math.min(window.innerWidth / STAGE_W, window.innerHeight / STAGE_H))
		fit()
		window.addEventListener('resize', fit)
		return () => window.removeEventListener('resize', fit)
	}, [])

	// Keep the hash in sync so a slide can be linked or reloaded.
	useEffect(() => { window.history.replaceState(null, '', `#${index + 1}`) }, [index])

	const next = useCallback(() => {
		if (step < slides[index].steps) setStep(step + 1)
		else if (index < slides.length - 1) { setIndex(index + 1); setStep(0) }
	}, [index, step, slides])

	const prev = useCallback(() => {
		if (step > 0) setStep(step - 1)
		else if (index > 0) { setIndex(index - 1); setStep(slides[index - 1].steps) }
	}, [index, step, slides])

	useEffect(() => {
		const onKey = (e: KeyboardEvent) => {
			if (['ArrowRight', 'ArrowDown', 'PageDown', ' ', 'Enter'].includes(e.key)) { e.preventDefault(); next() }
			else if (['ArrowLeft', 'ArrowUp', 'PageUp', 'Backspace'].includes(e.key)) { e.preventDefault(); prev() }
			else if (e.key === 'Home') { setIndex(0); setStep(0) }
			else if (e.key === 'End') { setIndex(slides.length - 1); setStep(slides[slides.length - 1].steps) }
			else if (e.key.toLowerCase() === 'n') setShowNotes(v => !v)
			else if (e.key.toLowerCase() === 'f') {
				if (document.fullscreenElement) document.exitFullscreen()
				else document.documentElement.requestFullscreen?.().catch(() => console.warn('Fullscreen request was refused'))
			}
		}
		window.addEventListener('keydown', onKey)
		return () => window.removeEventListener('keydown', onKey)
	}, [next, prev, slides])

	// Swipe navigation for touch screens.
	useEffect(() => {
		let x0: number | null = null
		const start = (e: TouchEvent) => { x0 = e.touches[0].clientX }
		const end = (e: TouchEvent) => {
			if (x0 == null) return
			const dx = e.changedTouches[0].clientX - x0
			if (Math.abs(dx) > 40) { if (dx < 0) next(); else prev() }
			x0 = null
		}
		window.addEventListener('touchstart', start)
		window.addEventListener('touchend', end)
		return () => { window.removeEventListener('touchstart', start); window.removeEventListener('touchend', end) }
	}, [next, prev])

	const slide = slides[index]
	const p = palette(slide.tool)
	const vars = { '--t-bg': p.bg, '--t-fg': p.fg, '--t-muted': p.muted, '--t-subtle': p.subtle, '--t-faint': p.faint, '--t-panel': p.panel } as CSSProperties

	return (
		<div
			role="region"
			aria-roledescription="slide deck"
			aria-label={title}
			onClick={e => { if ((e.target as HTMLElement).closest('a')) return; if (e.clientX < window.innerWidth / 3) prev(); else next() }}
			style={{ ...vars, position: 'fixed', inset: 0, zIndex: 100, background: 'var(--t-bg)', color: 'var(--t-fg)', transition: 'background-color 500ms ease, color 500ms ease', overflow: 'hidden', cursor: 'default', fontFamily: 'var(--font-sans)', fontWeight: 300 }}
		>
			<style>{BASE_CSS + css}</style>
			<div style={{ position: 'absolute', left: '50%', top: '50%', width: STAGE_W, height: STAGE_H, transform: `translate(-50%, -50%) scale(${scale})`, transformOrigin: 'center' }}>
				<div key={slide.id} role="group" aria-roledescription="slide" aria-label={`${index + 1} of ${slides.length}`} style={{ position: 'absolute', inset: 0, animation: 'vfd-in 500ms ease' }}>
					{slide.render(step)}
					{slide.footer && <Footer left={slide.footer} n={index + 1} total={slides.length} />}
				</div>
			</div>
			<div aria-hidden="true" style={{ position: 'absolute', left: 0, bottom: 0, height: 2, width: `${((index + 1) / slides.length) * 100}%`, background: 'var(--t-fg)', opacity: 0.1, transition: 'width 500ms ease' }} />
			{showNotes && (
				<div onClick={e => e.stopPropagation()} style={{ position: 'absolute', left: 24, right: 24, bottom: 24, maxHeight: '40%', overflow: 'auto', padding: '20px 28px', borderRadius: 12, background: 'rgba(0,0,0,.82)', color: '#f4f4f4', fontSize: 18, lineHeight: 1.55 }}>
					<p style={{ fontSize: 12, letterSpacing: '0.18em', textTransform: 'uppercase', opacity: 0.6, marginBottom: 8 }}>Notes · {index + 1}/{slides.length} · step {step}/{slide.steps}</p>
					{slide.notes}
				</div>
			)}
		</div>
	)
}

