// Minimal markdown renderer for a tool's talk paper: headings, paragraphs, lists, tables, quotes, inline links/emphasis/code, {{figure:name}} slots, and scroll-reveal classes from talk.css.
// Synced automatically by type-tools/scripts/sync-sites.mjs to sites that have site/src/content/talkScript.ts.
// DO NOT edit this file inside a submodule — edit type-tools/shared/talk/Prose.tsx instead.
import { Fragment, type ReactNode } from 'react'

/** Merriweather display style used for paper headings (Light 300, opsz tied to size, as on the sites). */
const SERIF = 'var(--font-merriweather), Georgia, serif'

/** Renders inline markdown: [links](url), **bold**, *italic*, `code`. */
function inline(text: string, key = 'i'): ReactNode[] {
	const out: ReactNode[] = []
	const re = /\[([^\]]+)\]\(([^)\s]+)\)|\*\*([^*]+)\*\*|\*([^*]+)\*|`([^`]+)`/g
	let last = 0
	let m: RegExpExecArray | null
	let n = 0
	while ((m = re.exec(text))) {
		if (m.index > last) out.push(text.slice(last, m.index))
		const k = `${key}-${n++}`
		if (m[1]) {
			const external = /^https?:/.test(m[2])
			out.push(<a key={k} href={m[2]} {...(external ? { target: '_blank', rel: 'noopener noreferrer' } : {})} className="underline decoration-foreground/30 underline-offset-4 hover:decoration-foreground transition-colors">{inline(m[1], k)}</a>)
		} else if (m[3]) out.push(<strong key={k} className="font-semibold">{inline(m[3], k)}</strong>)
		else if (m[4]) out.push(<em key={k}>{inline(m[4], k)}</em>)
		else if (m[5]) out.push(<code key={k} className="font-mono text-[0.85em] px-1 rounded" style={{ background: 'var(--panel)' }}>{m[5]}</code>)
		last = re.lastIndex
	}
	if (last < text.length) out.push(text.slice(last))
	return out
}

/** Splits a markdown table row into trimmed cells. */
function cells(line: string): string[] {
	return line.trim().replace(/^\||\|$/g, '').split('|').map(c => c.trim())
}

/** Slugifies a heading for in-page anchors. */
export function slug(text: string): string {
	return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

/** Renders a markdown string; `figures` maps {{figure:name}} slots to components. */
export default function Prose({ source, figures }: { source: string; figures: Record<string, ReactNode> }) {
	const lines = source.replace(/\r/g, '').split('\n')
	const blocks: ReactNode[] = []
	let i = 0
	while (i < lines.length) {
		const line = lines[i]
		const k = `b${i}`
		if (!line.trim()) { i++; continue }
		const fig = line.trim().match(/^\{\{figure:([\w-]+)\}\}$/)
		if (fig) { blocks.push(<figure key={k} className="paper-reveal my-4 -mx-2 lg:-mx-8">{figures[fig[1]]}</figure>); i++; continue }
		const h = line.match(/^(#{2,3})\s+(.*)$/)
		if (h) {
			const text = h[2]
			blocks.push(h[1] === '##'
				? <h2 key={k} id={slug(text)} className="paper-reveal scroll-mt-24 mt-16 text-3xl lg:text-5xl" style={{ fontFamily: SERIF, fontVariationSettings: '"wght" 300, "opsz" 72', lineHeight: 1.1, textWrap: 'balance' }}>{inline(text, k)}</h2>
				: <h3 key={k} id={slug(text)} className="paper-reveal scroll-mt-24 mt-8 text-xs uppercase tracking-[0.18em] font-medium text-muted">{inline(text, k)}</h3>)
			i++; continue
		}
		if (line.startsWith('|')) {
			const rows: string[][] = []
			while (i < lines.length && lines[i].startsWith('|')) { if (!/^\|\s*-/.test(lines[i])) rows.push(cells(lines[i])); i++ }
			const [head, ...body] = rows
			blocks.push(
				<div key={k} className="paper-reveal overflow-x-auto -mx-2 lg:-mx-8">
					<table className="w-full text-sm border-collapse">
						<thead><tr>{head.map((c, j) => <th key={j} className="text-left font-normal text-muted px-2 lg:px-3 py-2 border-b border-foreground/10">{inline(c, `${k}h${j}`)}</th>)}</tr></thead>
						<tbody>{body.map((r, ri) => <tr key={ri} className="odd:bg-foreground/[0.04]">{r.map((c, j) => <td key={j} className="align-top px-2 lg:px-3 py-2 text-muted first:text-foreground">{inline(c, `${k}r${ri}c${j}`)}</td>)}</tr>)}</tbody>
					</table>
				</div>
			)
			continue
		}
		if (/^(- |\d+\. )/.test(line)) {
			const ordered = /^\d+\. /.test(line)
			const items: string[] = []
			while (i < lines.length && /^(- |\d+\. )/.test(lines[i])) { items.push(lines[i].replace(/^(- (\[[ x]\] )?|\d+\. )/, '')); i++ }
			const Tag = ordered ? 'ol' : 'ul'
			blocks.push(<Tag key={k} className={`paper-reveal ${ordered ? 'list-decimal' : 'list-disc'} pl-5 flex flex-col gap-2 text-base leading-relaxed marker:text-faint`}>{items.map((t, j) => <li key={j}>{inline(t, `${k}l${j}`)}</li>)}</Tag>)
			continue
		}
		if (line.startsWith('> ')) {
			const quote: string[] = []
			while (i < lines.length && lines[i].startsWith('> ')) { quote.push(lines[i].slice(2)); i++ }
			blocks.push(<blockquote key={k} className="paper-reveal pl-5 border-l border-foreground/20 text-xl lg:text-2xl" style={{ fontFamily: SERIF, fontStyle: 'italic', fontVariationSettings: '"wght" 300, "opsz" 36', lineHeight: 1.4 }}>{inline(quote.join(' '), k)}</blockquote>)
			continue
		}
		const para: string[] = []
		while (i < lines.length && lines[i].trim() && !/^(#{2,3}\s|\||- |\d+\. |> |\{\{figure:)/.test(lines[i])) { para.push(lines[i]); i++ }
		blocks.push(<p key={k} className="paper-reveal text-base leading-relaxed" style={{ textWrap: 'pretty' }}>{inline(para.join(' '), k)}</p>)
	}
	return <>{blocks.map((b, j) => <Fragment key={j}>{b}</Fragment>)}</>
}
