// Shared 1200×630 Open Graph image for a tool's talk routes (/talk, /talk/transcript, /paper, /paper/data), in that tool's palette.
// Synced automatically by type-tools/scripts/sync-sites.mjs to sites that have site/src/content/talkScript.ts.
// DO NOT edit this file inside a submodule — edit type-tools/shared/talk/talkOg.tsx instead.
import { ImageResponse } from 'next/og'
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { ReactNode } from 'react'
import { toolBgHex, toolFgHex, toolFgMutedHex, toolFgSubtleHex } from '../../lib/toolColorsCore.mjs'

/** OG image dimensions in pixels. */
export const TALK_OG_SIZE = { width: 1200, height: 630 }

/** Options for one talk OG image. */
export interface TalkOgOptions {
	/** Tool id whose palette colours the card, e.g. 'vfClamp'. */
	tool: string
	/** Small uppercase label, e.g. 'The paper · vf-clamp'. */
	eyebrow: string
	/** Title line 1 (upright) and line 2 (italic, subtle). */
	title: [string, string]
	/** One-line footnote at the bottom left. */
	footnote: string
	/** Short URL shown at the bottom right, e.g. 'vfclamp.com/paper'. */
	path: string
	/** Optional tool-specific motif drawn above the title (Satori-compatible JSX). */
	motif?: ReactNode
}

/** Renders a talk OG image in the tool's palette. */
export async function talkOgImage({ tool, eyebrow, title, footnote, path, motif }: TalkOgOptions) {
	const interLight = await readFile(join(process.cwd(), 'public/fonts/inter-300.woff'))
	const [bg, fg, muted, subtle] = [toolBgHex(tool), toolFgHex(tool), toolFgMutedHex(tool), toolFgSubtleHex(tool)]
	return new ImageResponse(
		(
			<div style={{ background: bg, width: '100%', height: '100%', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', padding: '72px 80px', fontFamily: 'Inter, sans-serif' }}>
				<span style={{ fontSize: 15, letterSpacing: '0.18em', color: muted, textTransform: 'uppercase' }}>{eyebrow}</span>
				<div style={{ display: 'flex', flexDirection: 'column' }}>
					{motif && <div style={{ display: 'flex', marginBottom: 44 }}>{motif}</div>}
					<div style={{ fontSize: 84, color: fg, lineHeight: 1.04, fontWeight: 300 }}>{title[0]}</div>
					<div style={{ fontSize: 84, color: muted, lineHeight: 1.04, fontWeight: 300, fontStyle: 'italic' }}>{title[1]}</div>
				</div>
				<div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
					<span style={{ fontSize: 18, color: muted, letterSpacing: '0.02em' }}>{footnote}</span>
					<span style={{ fontSize: 15, color: subtle, letterSpacing: '0.04em' }}>{path}</span>
				</div>
			</div>
		),
		{ ...TALK_OG_SIZE, fonts: [{ name: 'Inter', data: interLight, style: 'normal', weight: 300 }] },
	)
}
