// CookieBanner — GDPR cookie consent banner for GA4 Consent Mode v2.
// Synced automatically by type-tools/scripts/sync-sites.mjs.
// DO NOT edit this file inside a submodule — edit type-tools/shared/components/CookieBanner.tsx instead.

'use client'

import { useState, useEffect } from 'react'

const STORAGE_KEY = 'cookie-consent'

/** Cookie consent banner. Shows once per browser; persists choice to localStorage. */
export default function CookieBanner() {
	const [visible, setVisible] = useState(false)

	useEffect(() => {
		try {
			if (!localStorage.getItem(STORAGE_KEY)) setVisible(true)
		} catch { /* storage blocked — stay hidden */ }
	}, [])

	function grant() {
		try { localStorage.setItem(STORAGE_KEY, 'granted') } catch { /* */ }
		// Update GA4 Consent Mode v2 for the current session if already loaded
		if (typeof (window as unknown as Window & { gtag?: (...args: unknown[]) => void }).gtag === 'function') {
			(window as unknown as Window & { gtag: (...args: unknown[]) => void }).gtag(
				'consent', 'update', { analytics_storage: 'granted' }
			)
		}
		setVisible(false)
	}

	function deny() {
		try { localStorage.setItem(STORAGE_KEY, 'denied') } catch { /* */ }
		setVisible(false)
	}

	if (!visible) return null

	return (
		<div
			role="dialog"
			aria-label="Cookie consent"
			// Fixed dark overlay (consistent across all tools) — uses fixed light text, not theme
			// vars, so it stays legible on both dark- and light-background sites.
			className="fixed bottom-0 left-0 right-0 z-50 border-t border-white/10 bg-black/90 backdrop-blur-sm px-4 py-3 flex flex-col sm:flex-row items-center gap-3 text-xs text-white"
		>
			<p className="flex-1 text-white/70">
				This site uses Google Analytics to understand how visitors use it. No personal data is shared beyond standard GA4 defaults.
			</p>
			<div className="flex gap-4 shrink-0">
				<button onClick={deny} className="px-3 py-1.5 rounded text-white/70 hover:text-white hover:bg-white/10 transition-colors">
					Decline
				</button>
				<button
					onClick={grant}
					className="px-3 py-1.5 rounded bg-white/15 text-white hover:bg-white/25 transition-colors"
				>
					Accept
				</button>
			</div>
		</div>
	)
}
